name: Automated Tests
on: [push]
jobs:
  find_lowest_number_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Test case 1 (10 numbers)
        run: python find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
      - name: Compare expected output to actual in test case 1
        run: diff test_data/test1_expected.txt test_data/test1_output.txt
      - name: Test case 2 (1 number)
        run: python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
      - name: Compare expected output to actual in test case 2
        run: diff test_data/test2_output.txt test_data/test2_expected.txt
      - name: Test case 3 (blank file)
        run: python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
      - name: Compare expected output to actual in test case 3
        run: diff test_data/test3_output.txt test_data/test3_expected.txt
